site_name: suru(dot)im
site_author: SuRu
site_url: https://suru.im

extra:
  homepage: https://suru.im
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/suru33
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/suru33
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/suru33/
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/~suru33
  analytics:
    provider: google
    property: G-5B77Q8KHX6
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    MacOS: mac
    Script: script
    Database: db

repo_url: https://github.com/suru33/hello-world
copyright: |
  Copyright &copy; 2022 - 2023 Surendra, 
  License <a style="color: white;" href="https://github.com/suru33/hello-world/blob/master/LICENSE">MIT</a>

theme:
  name: material
  custom_dir: overrides
  features:
    - content.tooltips
    - navigation.tracking
    - navigation.instant
    - content.tabs.link
    - navigation.expand
    - search.share
    - content.code.annotate
  font:
    text: Open Sans
    code: JetBrains Mono
  palette:
    primary: green
    accent: teal
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      mac: fontawesome/brands/apple
      script: fontawesome/solid/scroll
      db: fontawesome/solid/database

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: code
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags
  - git-revision-date-localized:
      locale: en
      type: datetime
      exclude:
        - index.md