site_name: suru∙im
site_author: SuRu
site_url: https://suru.im
repo_url: https://github.com/suru33/hello-world
repo_name: suru33/hello-world
copyright: |
  Copyright &copy; 2022 - 2023 <a style="color: white;" href="mailto:33urus+helloworld@gmail.com">Surendra</a>, License
  <a target="_blank" style="color: white;" href="https://github.com/suru33/hello-world/blob/master/LICENSE">MIT</a>

extra:
  homepage: https://suru.im
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/suru33
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/suru33
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/suru33/
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/~suru33
  analytics:
    provider: google
    property: G-5B77Q8KHX6
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    MacOS: mac
    Script: script
    Database: db

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  font:
    text: Source Sans Pro
    code: JetBrains Mono
  palette:
    primary: green
    accent: teal
  features:
    - content.tooltips
    - navigation.tracking
    - navigation.instant
    - content.tabs.link
    - navigation.expand
    - search.share
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  icon:
    repo: material/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      mac: fontawesome/brands/apple
      script: fontawesome/solid/scroll
      db: fontawesome/solid/database

extra_css:
  - extras/stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - extras/js/katex.js
  - extras/js/drawio-reload.js

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  #  https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # ---
  - toc:
      permalink: true
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: code
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags
  - git-revision-date-localized:
      locale: en
      type: datetime
      exclude:
        - index.md
  - open-in-new-tab
