site_name: SuRu
extra:
  homepage: https://suru.im
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/suru33
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/suru33
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/suru33/
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/~suru33
  analytics:
    provider: google
    property: G-5B77Q8KHX6

repo_url: https://github.com/suru33/hello-world
copyright: Copyright &copy; 2022 - 2023 Surendra

theme:
  name: material
  custom_dir: overrides
  features:
    - content.tooltips
    - navigation.tracking
    - navigation.instant
    - content.tabs.link
    - navigation.expand
    - search.share
  font:
    text: Open Sans
    code: JetBrains Mono
  palette:
    primary: green
    accent: teal
  logo: assets/logo.png
  favicon: assets/favicon.png

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      locale: en
      type: datetime
      exclude:
        - index.md